### ISSUE TITLE
CRUD

### ISSUE THREAD

**Issue by bissisoft** [bissisoft/vps#15]
- Implement full CRUD functionalities for the user's "view points"

1. Use the user's storage hub to **C**reate, **R**ead, **U**pdate, and **D**elete the "view points"

2. The owner users must have full CRUD of their own "view points" and only Read for the other users' published "view points"

3. Public (or users not signed in) have only Read rights to **the published** "view points" and no visibility to the the unpiblished (or encrypted) ones

**Comment by emilsergiev** [comment]
will take longer because gaia.blockstack.org certificate has expired today :cry: 
ticket has been sent so they should resolve the issue soon :smiley:

**Comment by bissisoft** [comment]
> will take longer because gaia.blockstack.org certificate has expired today :cry:
> ticket has been sent so they should resolve the issue soon :smiley:

It's fixed now. You may resume the good work you do. Rapido! Rapido! :fast_forward:

**Comment by emilsergiev** [comment]
**create** and **read** from the CRUD is done ^.^ 
also, fixed the redirect bug that you found, refactored the users board, and made some new improvements...
let's merge the changes to the master and finish the **update** and **delete** part of the CRUD next
