### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by bissisoft** [bissisoft/vps#16]
- Implement an input field in the AppBar to search for Blockstack users

- [ ] Drops down a list of auto-suggestions when you start typing in the search field

- [ ] Let's limit the drop-down list with up to 7 users (more than 7 will not be good for the mobile version)

- [ ] On select (on click of an username from the list) redirects you to that user's personal "profile" page

**Comment by emilsergiev** [comment]
gaia.blockstack.org certificate has expired today so the api does not work at the moment...
ticket has been sent so hopefully they will fix that soon :wink:

**Comment by bissisoft** [comment]
> gaia.blockstack.org certificate has expired today so the api does not work at the moment...
> ticket has been sent so hopefully they will fix that soon :wink:

Fixed :rocket:
